options:
  logging: "CLOUD_LOGGING_ONLY"

steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      [
        'gsutil',
        '-m',
        'rsync',
        '-r',
        'build/',
        'gs://travelsmart-frontend'
      ]
timeout: '600s'
